import { useEffect, useMemo, useState } from "react";
import { Download, FileText, Package, ReceiptText, Users } from "lucide-react";
import { api } from "../services/api";
import "../styles/relatorios.css";
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
function dataLocalISO(data){const d=new Date(data);const offset=d.getTimezoneOffset();return new Date(d.getTime()-offset*60000).toISOString().slice(0,10)}
export default function Relatorios(){
 const [pedidos,setPedidos]=useState([]),[inicio,setInicio]=useState(""),[fim,setFim]=useState(""),[carregando,setCarregando]=useState(true);
 useEffect(()=>{api.get("/pedidos").then(r=>setPedidos(r.data)).catch(console.error).finally(()=>setCarregando(false))},[]);
 const dados=useMemo(()=>{const lista=pedidos.filter(p=>{const d=dataLocalISO(p.createdAt);return(!inicio||d>=inicio)&&(!fim||d<=fim)});const concluidos=lista.filter(p=>p.status==="ENTREGUE");const faturamento=concluidos.reduce((s,p)=>s+Number(p.total),0);const ticket=concluidos.length?faturamento/concluidos.length:0;const clientes=new Set(lista.map(p=>p.clienteId)).size;const produtos={};lista.forEach(p=>p.itens?.forEach(i=>{const nome=i.produto?.nome||"Produto";produtos[nome]=(produtos[nome]||0)+i.quantidade}));return{lista,concluidos,faturamento,ticket,clientes,produtos:Object.entries(produtos).sort((a,b)=>b[1]-a[1]).slice(0,5)}} ,[pedidos,inicio,fim]);
 function exportarCSV(){const linhas=[["Pedido","Data","Cliente","Status","Pagamento","Total"],...dados.lista.map(p=>[`#${p.id}`,new Date(p.createdAt).toLocaleDateString("pt-BR"),p.cliente?.nome||"",p.status,p.formaPagamento||"",Number(p.total).toFixed(2).replace(".",",")])];const blob=new Blob(["\ufeff"+linhas.map(l=>l.map(v=>`"${String(v).replaceAll('"','""')}"`).join(";")).join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="relatorio-pedidos.csv";a.click();URL.revokeObjectURL(url)}
 return <section className="reports-page"><div className="reports-heading"><div><p className="eyebrow">ANÁLISE</p><h1>Relatórios</h1><p>Entenda os resultados da sua operação.</p></div><button onClick={exportarCSV} disabled={!dados.lista.length}><Download size={17}/> Exportar CSV</button></div><div className="report-filters"><label>De<input type="date" value={inicio} onChange={e=>setInicio(e.target.value)}/></label><label>Até<input type="date" value={fim} onChange={e=>setFim(e.target.value)}/></label><button onClick={()=>{setInicio("");setFim("")}}>Limpar período</button></div>{carregando?<p className="report-loading">Carregando dados...</p>:<><div className="report-metrics"><Metric icon={ReceiptText} label="Faturamento entregue" value={money.format(dados.faturamento)} tone="orange"/><Metric icon={Package} label="Pedidos no período" value={dados.lista.length} tone="amber"/><Metric icon={FileText} label="Ticket médio" value={money.format(dados.ticket)} tone="blue"/><Metric icon={Users} label="Clientes atendidos" value={dados.clientes} tone="green"/></div><div className="report-grid"><section className="report-panel"><div className="report-panel-head"><div><h2>Produtos mais vendidos</h2><p>Quantidade de itens no período</p></div><Package size={19}/></div>{dados.produtos.length?dados.produtos.map(([nome,qtd],i)=><div className="product-rank" key={nome}><span>{i+1}</span><b>{nome}</b><i/><strong>{qtd} un.</strong></div>):<p className="report-empty">Ainda não há pedidos no período selecionado.</p>}</section><section className="report-panel"><div className="report-panel-head"><div><h2>Resumo dos pedidos</h2><p>Situação no período selecionado</p></div><ReceiptText size={19}/></div><div className="status-summary">{[["Aguardando","PENDENTE"],["Em preparo","EM_PREPARO"],["Prontos","PRONTO"],["Entregues","ENTREGUE"]].map(([l,s])=><div key={s}><span className={s}/><p>{l}</p><b>{dados.lista.filter(p=>p.status===s).length}</b></div>)}</div></section></div></>}</section>;
}
function Metric({icon:Icon,label,value,tone}){return <article className={`report-metric ${tone}`}><span><Icon size={20}/></span><p>{label}</p><b>{value}</b></article>}
